### ISSUE TITLE
Repeat message due to http_timeout Slack error and two subsequent retries

### ISSUE THREAD

**Issue by tomerovadia** [tomerovadia/VoterHelpLine#92]
![image (3)](https://user-images.githubusercontent.com/15622817/95291845-5612cf80-083e-11eb-91e9-74f92c05a3e1.png)

Lauren was demoing the prod environment and received a text message twice. Postgres shows the message three times, and two are retries:

`SELECT * FROM messages WHERE message LIKE '%probably fine%';`

1	"http_timeout"	"delivered"	"2020-10-06 22:59:30.964548+00"
2	"http_timeout"	"delivered"	"2020-10-06 23:00:30.485861+00"
3      null	                         "delivered"     "2020-10-06 22:59:28.193453+00"

Sentry caught this too, via the emoji reactions: `SLACKAPIUTIL.addSlackMessageReaction: ERROR in adding reaction: already_reacted`
https://sentry.io/organizations/voteamerica/issues/1940321582/events/f4d405441c9b445fa1e1bd7a54aa3b2f/

**Comment by tomerovadia** [comment]
@benweissmann have any hypotheses as to what might have happened here?

**Comment by benweissmann** [comment]
Closing this out; should be fixed with the deduplication logic
